spring:
  datasource:
    url: jdbc:mysql://192.168.0.67:3306/hbs?serverTimezone=Asia/Seoul
    username: HBS
    password: ucp87411!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
