import { HbsContent } from '../../types/HbsContent';

export const dummyContents: HbsContent[] = [
  {
    fileId: 1,
    title: '효성 HBS 홍보 영상',
    description: '효성의 브랜드를 소개하는 공식 영상입니다.',
    fileUrl: 'https://cdn.hsb.com/videos/hsb_promo_1.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=HBS+Promo+1',
    extension: 'mp4',
    dispSeq: 1,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2025-04-01',
    fileType: 'VIDEO',
    contentType: 'HBS',
  },
  {
    fileId: 2,
    title: 'CI 소개 영상',
    description: 'CI/BI 브랜드 소개와 활용 가이드 영상입니다.',
    fileUrl: 'https://cdn.hsb.com/videos/ci_intro.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=CI+Intro',
    extension: 'mp4',
    dispSeq: 2,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2025-04-03',
    modifyDate: '2025-04-05',
    fileType: 'VIDEO',
    contentType: 'CI_BI',
  },
  {
    fileId: 3,
    title: '사내 행사 영상',
    description: '2024년 사내 행사 영상 스케치입니다.',
    fileUrl: 'https://cdn.hsb.com/videos/internal_event.mp4',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=Event+2024',
    extension: 'mp4',
    dispSeq: 3,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2024-12-31',
    delDate: undefined,
    fileType: 'VIDEO',
    contentType: 'PROMO',
  },
  {
    fileId: 4,
    title: '효성 로고 이미지',
    description: '공식 로고 PNG 파일입니다.',
    fileUrl: 'https://cdn.hsb.com/images/logo.png',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=HSB+Logo',
    extension: 'png',
    dispSeq: 4,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2025-03-15',
    fileType: 'IMAGE',
    contentType: 'CI_BI',
  },
  {
    fileId: 5,
    title: '브랜드 가이드 문서',
    description: '효성 브랜드 가이드 문서 PDF 버전입니다.',
    fileUrl: 'https://cdn.hsb.com/docs/brand-guide.pdf',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=PDF+Doc',
    extension: 'pdf',
    dispSeq: 5,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2025-02-28',
    fileType: 'DOCUMENT',
    contentType: 'CI_BI',
  },
  {
    fileId: 6,
    title: '사내 홍보 포스터',
    description: '2025 상반기 캠페인 이미지 포스터입니다.',
    fileUrl: 'https://cdn.hsb.com/images/poster.jpg',
    thumbnailUrl: 'https://via.placeholder.com/400x250.png?text=Poster+2025',
    extension: 'jpg',
    dispSeq: 6,
    useTF: 'Y',
    delTF: 'N',
    regDate: '2025-04-10',
    fileType: 'IMAGE',
    contentType: 'PROMO',
  }
];
